# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:
  nginx:
    container_name: nginx_demo_container
    restart: always
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
     - ./client/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask

  flask:
    container_name: flask_demo_container
    restart: always
    image: flask
    build: ./server
    volumes:
    - ./server:/usr/src/app/server
    env_file:
     - .env
    depends_on:
      rabbit:
        condition: service_healthy
    links: 
        - rabbit

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: vrenko-bitfinex
      MYSQL_USER: vrenko-bitfinex
      MYSQL_PASSWORD: Complicated11Admin22Password33
